trigger:
- master

pool:
  # This is the name of the agent pool to run the tests on
  name: Jetson

stages:
  - stage: Test
    jobs:
    - job: Test
      displayName: Builds and tests program
      steps:
      # Pull the docker image. When a self-hosted agent is used,
      # this should be cashed between runs to minimize excessive downloading and speeding up the build.
      - script: docker pull emwjacobson/cudatester
        displayName: 'Pulls the latest version of cudatester'
      # Run 'make' inside of the container 
      - script: docker run --rm -v `pwd`:/app/copy emwjacobson/cudatester:latest make
        displayName: 'Runs our program'
