trigger:
- master
- suite

pool:
  # This is the name of the agent pool to run the tests on
  name: Jetson

stages:
  - stage: Test
    jobs:
    - job:
      displayName: Runs my CUDA program
      steps:
      - script: make -j -k -C MySampleProgram
        displayName: 'Runs our program'
    - job:
      displayName: Compiles Nvidias cuda-samples
      steps:
      - checkout: self
        submodules: recursive
      - script: make -i -j -k -C cuda-samples
        displayName: 'Makes nvidias cuda-samples'
    - job:
      displayName: Compiles Nvidias cuda_benchmark
      steps:
      - checkout: self
        submodules: recursive
      - script: cd cuda_benchmark && sed -i 's/3.13/3.10/' CMakeLists.txt
      - script: cmake .
      - script: make
        displayName: Makes program
