trigger:
- master

pool:
  # This is the name of the agent pool to run the tests on
  name: Jetson

stages:
  - stage: Test
    jobs:
    - job:
      displayName: Runs my CUDA program
      steps:
      - script: make
        displayName: 'Runs our program'
    - job:
      displayName: Compiles Nvidias cuda-samples
      steps:
      - script: make -j -C cuda-samples
        displayName: 'Makes nvidias cuda-samples'
