trigger:
- master
- profiler

pool:
  # This is the name of the agent pool to run the tests on
  name: Jetson

stages:
  - stage: Test
    jobs:
    
    - job:
      displayName: Runs my CUDA program
      steps:
      - script: make -j -k -C MySampleProgram
        displayName: 'Runs our program'
      - script: mkdir out && nvprof -o out/profiler.nvvp ./MySampleProgram/cudaProgram
        displayName: 'Creates visual profiler log'
      - script: nvprof --log-file out/log.txt ./MySampleProgram/cudaProgram
        displayName: 'Creates output log'
      - script: ./check.sh ./MySampleProgram/cudaProgram | tee out/result.txt
        displayName: 'Check which features are used'
      - publish: ./out
        artifact: 'Sample Logs'

    - job:
      displayName: Stream Test
      steps:
      - script: make -j -C UnifiedMemoryStreams
        displayName: 'Makes UnifiedMemoryStreams'
      - script: mkdir out && nvprof -o out/profiler.nvvp ./UnifiedMemoryStreams/UnifiedMemoryStreams
        displayName: 'Creates visual profiler log'
      - script: nvprof --log-file out/log.txt ./UnifiedMemoryStreams/UnifiedMemoryStreams
        displayName: 'Creates output log'
      - script: ./check.sh ./UnifiedMemoryStreams/UnifiedMemoryStreams | tee out/result.txt
        displayName: 'Check which features are used'
      - publish: ./out
        artifact: 'UnifiedMemoryStreams Logs'
