trigger:
- master
- suite

pool:
  # This is the name of the agent pool to run the tests on
  name: Jetson

stages:
  - stage: Test
    jobs:
    - job:
      displayName: Runs my CUDA program
      steps:
      - script: make -j -k -C MySampleProgram
        displayName: 'Runs our program'
    - job:
      displayName: Compiles Nvidias cuda-samples
      steps:
      - checkout: self
        submodules: recursive
      - script: make -i -j -k -C cuda-samples
        displayName: 'Makes nvidias cuda-samples'
    - job:
      displayName: Complies mixbench
      steps:
      - checkout: self
        submodules: recursive
      - script: cmake ./mixbench/mixbench-cuda
      - script: make -j
      - script: ./mixbench-cuda-ro
    - job:
      displayName: Complie tensorflow lite
      steps:
      - checkout: self
        submodules: recursive
      - script: ./tensorflow/tensorflow/lite/tools/make/download_dependencies.sh
      - script: sed -i 's/NO_JOB=4/NO_JOB=10/' ./tensorflow/tensorflow/lite/tools/make/build_aarch64_lib.sh
      - script: ./tensorflow/tensorflow/lite/tools/make/build_aarch64_lib.sh
