trigger:
- master
- suite

pool:
  # This is the name of the agent pool to run the tests on
  name: Jetson

stages:
  - stage: Test
    jobs:
    - job:
      displayName: Runs my CUDA program
      steps:
      - script: make -j -k -C MySampleProgram
        displayName: 'Runs our program'
    - job:
      displayName: Compiles Nvidias cuda-samples
      steps:
      - checkout: self
        submodules: recursive
      - script: make -j -k -C cuda-samples
        displayName: 'Makes nvidias cuda-samples'
