trigger:
- master

pool:
  # This is the name of the agent pool to run the tests on
  name: Jetson

stages:
  - stage: Test
    jobs:
    - job: Test
      displayName: Builds and tests program
      steps:
      # Run 'make' inside of the container 
      - script: make
        displayName: 'Runs our program'
